# version: "3.8"

services:
  postgres:
    container_name: db-transcritor
    image: postgres:13
    environment:
      POSTGRES_DB: "transcritor"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345678"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Executa automaticamente
    ports:
      - "5432:5432"

  # ollama:
  #   container_name: ollama-server
  #   image: ollama/ollama:latest
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama_data:/root/.ollama

  # app:
  #   image: speech-to-text:1.1
  #   container_name: app-transcritor
  #   build: .
  #   depends_on:
  #     - postgres
  #     - ollama
  #   ports:
  #     - "8501:8501" 
  #   environment:
  #     - OLLAMA_HOST=http://ollama:11434

volumes:
  postgres_data:
  ollama_data: