services:
  postgres:
    container_name: cuda-db-transcritor
    image: postgres:13
    environment:
      POSTGRES_DB: "transcritor"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345678"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped

  ollama:
    container_name: ollama-server
    image: ollama/ollama:latest
    ports:
      - "11435:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    entrypoint: ["/bin/sh", "-c", "ollama serve & sleep 5 && ollama pull qwen2.5:7b && ollama pull gemma2:9b && wait"]

  app:
    build: .
    container_name: cuda-app-transcritor
    depends_on:
      - postgres
      - ollama
    environment:
      - DATABASE_URL=postgresql://postgres:12345678@cuda-db-transcritor:5432/transcritor
      - OLLAMA_HOST=http://ollama-server:11434
      - HF_TOKEN=hf_seu_token
      - OLLAMA_TIMEOUT=600
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    restart: unless-stopped
volumes:
  postgres_data:
  ollama_data:
