# version: "3.8"

services:
  postgres:
    container_name: db-transcritor
    image: postgres:13
    environment:
      POSTGRES_DB: "transcritor"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345678"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Executa automaticamente
    ports:
      - "5432:5432"

  app:
    image: speech-to-text:1.0
    container_name: app-transcritor
    # build: .
    depends_on:
      - postgres
    ports:
      - "8501:8501" 
volumes:
  postgres_data:
